name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Run ipconfig
      id: ip_step
      shell: cmd
      run: |
        ipconfig
        FOR /F "tokens=2 delims=:" %%a in ('ipconfig ^| find "IPv4"') do (
          echo "server_ip=%%a" >> %GITHUB_ENV%
        )

    - name: Start outrun.exe
      shell: cmd
      run: |
        echo "Using IP: %server_ip%"
        start /b outrun.exe
