name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Run ipconfig
      run: ipconfig

    - name: Start outrun.exe
      run: start /b outrun.exe

    - name: Echo server information
      run: echo "Server is running at: ${{ env.server_ip }}"
