name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Run ipconfig
      run: ipconfig
      id: ip_step
      shell: cmd
      run: |
        FOR /F "tokens=2 delims=:" %%a in ('ipconfig ^| find "IPv4"') do set SERVER_IP=%%a
        echo "server_ip=%SERVER_IP%" >> $GITHUB_ENV

    - name: Start outrun.exe
      run: start /b outrun.exe

    - name: Echo server information
      run: echo "Server is running at: ${{ env.server_ip }}"
